Реализация микросервиса
web-standards-ru/calendar-bot pull request #15
Opened 2020-06-04 18:14 UTC by dmitriym09

Реализация микросервиса для отправка сообщений о событиях календаря.

@pepelsbey

2020-06-24 23:00 UTC, pepelsbey commented
К сожалению, я не готов провести ревью, у меня просто нет квалификации. Подумаю, кого можно привлечь.

2020-06-24 23:01 UTC, pepelsbey commented
@h4 глянешь? :)

2020-06-28 16:03 UTC, h4 commented
А зачем вообще тут микросервис? Что это даст?

Пулл-риквест слишком большой и я слишком далеко ушёл от node.js, так что не готов провести качественный код-ревью. А поверхностный никому не нужен, как мне кажется.

2020-07-04 06:44 UTC, dmitriym09 commented
> А зачем вообще тут микросервис? Что это даст?
> 
> Пулл-риквест слишком большой и я слишком далеко ушёл от node.js, так что не готов провести качественный код-ревью. А поверхностный никому не нужен, как мне кажется.

Микросервис нужен для контроля отпралвенных постов.

2021-01-13 15:15 UTC, pepelsbey commented
> Реализация микросервиса для отправка сообщений о событиях календаря.

К сожалению, я не знаю, что делает этот пулреквест. Это объёмный код, который реализует какую-то задачу. Как он будет работать, что нужно дополнительно, кроме как смёржить — всей этой информации нет. Фраза «реализует микросервис», к сожалению, недостаточно подробно описывает весь написанный код.

2021-01-13 15:24 UTC, pepelsbey commented
Я попросил ещё людей посмотреть на код, но мне кажется тут два варианта есть всё равно:

1. Просто смёржить его и посмотреть, как работает. Но даже это непонятно: нужно что-то куда-то ставить и поднимать или оно всё само заработает? Никто не знает.
2. Созвониться и проговорить всё, что здесь происходит — и тогда станет понятно, куда идти.

Повторюсь, изначальный объём кода и постановка вопроса «нужно ревью» привели к такой длительной паузе. Но буду очень раз, если мы сможем это сдвинуть и чат заработает как планировали, код не пропадёт и все буду счастливы.

2021-01-13 15:56 UTC, dmitriym09 commented
Первый вариант оповещения о событиях в телеграм (был сделан как этап CD еще на travis) не был перенесен при переходе на Github Actions. И как раз появился сервер у Веб-стандартов. Я предложил допилить просто отправлялку отформатированного сообщения о событии в микросервис, который контролирует обновления данных о запощенных событиях (удаляет старое сообщение и постит новое). Вроде все согласились.

 PR получился таким большим, т.к. большая задача.

Микросервис в docker-контейнере. Ожидается, что при любых изменениях в основной ветке микросервис будет информирован путем вызова его HTTP API. После вызова API выгружаются все события календаря, проверяются, какие изменения были. Новые заново постятся, измененные удаляются и постятся заново.

Сейчас глянул и увидел недоделки:
- нет описания работы в README;
- нет docker-compose.yml;
- хорош бы вызывать обработку календаря в критической секции.

Я готов это все доделать, если канал с событиями кому-то нужен. Если он будет запускаться на ресурсах Веб-стандартов, то скажите, что именно для этого нужно. Или я могу вообще запустить на своих ресурсах (сейчас так и работает, мне приходят уведомления в мой личный канал).

2021-01-15 01:52 UTC, jt3k commented
привет! Действительно ли есть необходимость делать отправку в телеграм используя свой императивный код?
helpers/telegram.mjs

Есть отличная библиотека https://github.com/telegraf/telegraf/ 
и обёртка для неё https://github.com/telegraf/micro-bot

с этим инструментом 
→ наш объём кода уменьшится,
→ не придётся искать разработчика который починит наш скрипт если вдруг он перестанет работать (потому-что telegraf имеет кучу контрибутеров)

2021-01-15 08:02 UTC, dmitriym09 commented
> привет! Действительно ли есть необходимость делать отправку в телеграм используя свой императивный код?
> helpers/telegram.mjs
> 
> Есть отличная библиотека https://github.com/telegraf/telegraf/
> 
> с этим инструментом
> → наш объём кода уменьшится,
> → не придётся искать разработчика который починит наш скрипт если вдруг он перестанет работать (потому-что telegraf имеет кучу контрибутеров)
> 
> p.s. Ваш код написан хорошо, но возможны риски

Такой подход конечно имеет право на жизнь, но в данной ситуации я с ним согласен. Будем заменено 6 строчек код (может 22, если в либках ретрай сделан), а при немаленькая библиотека, 99% которой не имеет смысла использовать. При этом это не костыли, а вызов документированного API. Если он пререстанет корректно работать, то значит телеграм нарушила обратную совместимость. Такое, конечно, возможно, но маловероятно.

2021-01-16 17:51 UTC, amel-true requested changes
Спасибо за работу! Мне нравится сама идея, тут вопрос к Вадиму есть ли ресурсы для поднятия докер-контейнера?

Оставил несколько замечаний по коду.

2021-01-16 17:51 UTC, amel-true commented on helpers/telegram.mjs
> +    return await request(
В данном случае await не нужен

2021-01-16 17:51 UTC, amel-true commented on helpers/scan_event.mjs
> +            if (result == ProcessEventStatus.ok) {
Лучше всегда использовать строгое равенство

2021-01-16 17:51 UTC, amel-true commented on helpers/telegram.mjs
> +                            res.headers['content-type'] === 'application/json'
лучше вынести в переменную — легче будет читаться. 
Можно сократить через опшионал чейнинг ```res.headers?.['content-type']```

2021-01-16 17:51 UTC, amel-true commented on helpers/telegram.mjs
> +    return await request(
В данном случае await не нужен

2021-01-16 17:51 UTC, amel-true commented on helpers/telegram.mjs
> +        throw TypeError(`markdown ${markdown}`);
семантически правильнее ```new Error```

2021-01-16 17:51 UTC, amel-true commented on helpers/telegram.mjs
> +    if (typeof msgId !== 'number') {
Безопаснее проверить через Number.isInteger()

2021-01-16 17:51 UTC, amel-true commented on helpers/telegram.mjs
> +const MAX_RETRY = 100;
Лучше поднять наверх или вынести в отдельный файл с константами.

2021-01-16 17:51 UTC, amel-true commented on helpers/telegram.mjs
> + * Декортатор, гарантирующий повторный запрос при 429 ответе.
Опечатка, Декоратор

2021-01-16 17:51 UTC, amel-true commented on helpers/telegram.mjs
> +                        : 100,
Магическое число лучше вынести в константу и написать комментарий, почему такое значение, иначе непонятно, это требования API или эмпирически подобранное число.

2021-01-16 17:51 UTC, amel-true commented on index.mjs
> +send().finally(() => {});
Пустой finally

2021-01-16 17:51 UTC, amel-true commented on db.mjs
> +    `,
Для упрощения чтения и поддержки предлагаю вынести в отдельный файл шаблоны SQL-запросов.

2021-01-16 17:51 UTC, amel-true commented on db.mjs
> +    if (rows.length == 0) {
Нестрогое равенство. Предлагаю добавить в линтер проверку на нестрогие сравнения.

2021-01-16 17:51 UTC, amel-true commented on helpers/get_events.mjs
> +export default function () {
Лучше никогда не использовать export default — это усложнит дальнейший рефакторинг. Предлагаю запретить в линтере.

2021-01-16 17:51 UTC, amel-true commented on server.mjs
> +    app.use((req, _, next) => {
Лучше указать res, семантика _ у большинства связана с lodash, может ввести в заблуждение

2021-01-16 17:51 UTC, amel-true commented on server.mjs
> +    app.use((err, _, res) => {
Лучше указать err, req, res, next —> так визуально сразу считывается error middleware

2021-01-16 17:51 UTC, amel-true commented on server.mjs
> +    return {
кажется, что вызывается только в тестах (и никак не используется). Лучше не делать API для тестов.

2021-01-18 21:13 UTC, jt3k commented on helpers/get_events.mjs
> +export default function () {
А можете пояснить почему усложнит ?

2021-01-20 19:26 UTC, amel-true commented on helpers/get_events.mjs
> +export default function () {
Экспорт по умолчанию может быть импортирован в любую переменную. Никакой авторефакторинг не сможет это отследить, поиск по проекту не даст результатов — мы не знаем, в какую переменную будет импортирован код. Не будет работать и автокомплит. 

Плюсов же у этого подхода не видно.

2021-01-20 19:29 UTC, amel-true commented on helpers/get_events.mjs
> +import https from 'https';
не стоит использовать такие имена как helpers или utils, так как они провоцируют складывать вообще всё что угодно. Предлагаю отделить работу с events в папку events

2024-07-17 22:50 UTC, closed without merging